version: '3'

services:
  db:
    #platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nginxnode 

  app:
    build:
      context: node
    container_name: app
    hostname: node
    entrypoint: wait-for db:3306 -t 60 -- docker-entrypoint.sh node index.js
    tty: true  
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - nginxnode
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
    build:
      context: nginx
    container_name: nginx
    ports:
      - "8080:8080"
    depends_on:
      - app
    networks:
      - nginxnode                

networks:
  nginxnode:
    driver: bridge